import frontEndCategoryIcon from "../assets/icons/frontEndCategoryIcon.svg";
import juniordevopsIcon from "../assets/icons/juniordevopsIcon.svg";
import uiuxIcon from "../assets/icons/uiuxIcon.svg";
import categoriesIcon from "../assets/icons/categoriesIcon.svg";

export const CATEGORIES = [
  {
    id: "web-frontend",
    name: "Web Frontend",
    group: "Development",
    jobs: 140,
    subscribers: 273,
    icon: frontEndCategoryIcon,
    description: "All job posts related to frontend development.",
  },
  {
    id: "backend-database",
    name: "Backend & Database",
    group: "Development",
    jobs: 140,
    subscribers: 273,
    icon: juniordevopsIcon,
    description: "Backend and database engineering roles.",
  },
  {
    id: "uiux-product-design",
    name: "UI/UX & Product Design",
    group: "Design & Art",
    jobs: 78,
    subscribers: 1045,
    icon: uiuxIcon,
    description: "Design-focused roles including UI/UX and product design.",
  },
  {
    id: "machine-learning",
    name: "Machine Learning",
    group: "Development",
    jobs: 140,
    subscribers: 273,
    icon: categoriesIcon,
    description: "Machine learning and AI related jobs.",
  },
  {
    id: "mobile-application",
    name: "Mobile Application",
    group: "Development",
    jobs: 140,
    subscribers: 273,
    icon: categoriesIcon,
    description: "Mobile app development roles.",
  },
  {
    id: "web-full-stack",
    name: "Web Full-Stack",
    group: "Development",
    jobs: 140,
    subscribers: 273,
    icon: categoriesIcon,
    description: "Full-stack development positions.",
  },
  {
    id: "qa-devops-engineer",
    name: "QA & DevOps Engineer",
    group: "Development",
    jobs: 140,
    subscribers: 273,
    icon: categoriesIcon,
    description: "QA and DevOps engineering roles.",
  },
  {
    id: "security",
    name: "Security",
    group: "Development",
    jobs: 140,
    subscribers: 273,
    icon: categoriesIcon,
    description: "Cybersecurity and infrastructure security jobs.",
  },
  {
    id: "data-science",
    name: "Data Science",
    group: "Development",
    jobs: 96,
    subscribers: 812,
    icon: categoriesIcon,
    description: "Data analysis, statistics, and data-driven roles.",
  },
  {
    id: "cloud-engineering",
    name: "Cloud Engineering",
    group: "Development",
    jobs: 74,
    subscribers: 529,
    icon: categoriesIcon,
    description: "Cloud infrastructure and platform engineering jobs.",
  },
  {
    id: "blockchain",
    name: "Blockchain",
    group: "Development",
    jobs: 41,
    subscribers: 306,
    icon: categoriesIcon,
    description: "Blockchain development and Web3 roles.",
  },
  {
    id: "game-development",
    name: "Game Development",
    group: "Development",
    jobs: 58,
    subscribers: 477,
    icon: categoriesIcon,
    description: "Game design and development careers.",
  },
  {
    id: "desktop-application",
    name: "Desktop Application",
    group: "Development",
    jobs: 36,
    subscribers: 221,
    icon: categoriesIcon,
    description: "Desktop software development roles.",
  },
  {
    id: "technical-writing",
    name: "Technical Writing",
    group: "Content",
    jobs: 29,
    subscribers: 198,
    icon: categoriesIcon,
    description: "Documentation, tutorials, and technical content writing.",
  },
  {
    id: "content-creation",
    name: "Content Creation",
    group: "Marketing",
    jobs: 67,
    subscribers: 654,
    icon: categoriesIcon,
    description: "Creative content for blogs, social media, and platforms.",
  },
  {
    id: "digital-marketing",
    name: "Digital Marketing",
    group: "Marketing",
    jobs: 88,
    subscribers: 903,
    icon: categoriesIcon,
    description: "SEO, ads, growth, and digital campaign roles.",
  },
  {
    id: "product-management",
    name: "Product Management",
    group: "Business",
    jobs: 52,
    subscribers: 711,
    icon: categoriesIcon,
    description: "Product strategy, roadmaps, and management roles.",
  },
  {
    id: "business-analysis",
    name: "Business Analysis",
    group: "Business",
    jobs: 45,
    subscribers: 382,
    icon: categoriesIcon,
    description: "Business requirements and process analysis jobs.",
  },
  {
    id: "customer-support",
    name: "Customer Support",
    group: "Operations",
    jobs: 120,
    subscribers: 1440,
    icon: categoriesIcon,
    description: "Customer success and technical support roles.",
  },
  {
    id: "virtual-assistant",
    name: "Virtual Assistant",
    group: "Operations",
    jobs: 63,
    subscribers: 734,
    icon: categoriesIcon,
    description: "Remote administrative and assistant roles.",
  },
  {
    id: "project-management",
    name: "Project Management",
    group: "Business",
    jobs: 57,
    subscribers: 498,
    icon: categoriesIcon,
    description: "Project coordination and delivery roles.",
  },
  {
    id: "sales-business-development",
    name: "Sales & Business Development",
    group: "Business",
    jobs: 102,
    subscribers: 882,
    icon: categoriesIcon,
    description: "Sales growth and client acquisition roles.",
  },
  {
    id: "human-resources",
    name: "Human Resources",
    group: "Business",
    jobs: 34,
    subscribers: 275,
    icon: categoriesIcon,
    description: "Recruitment, HR operations, and people management.",
  },
  {
    id: "finance-accounting",
    name: "Finance & Accounting",
    group: "Business",
    jobs: 49,
    subscribers: 418,
    icon: categoriesIcon,
    description: "Accounting, bookkeeping, and financial roles.",
  },
  {
    id: "education-training",
    name: "Education & Training",
    group: "Education",
    jobs: 71,
    subscribers: 690,
    icon: categoriesIcon,
    description: "Teaching, tutoring, and course creation roles.",
  },
  {
    id: "research-analysis",
    name: "Research & Analysis",
    group: "Education",
    jobs: 27,
    subscribers: 214,
    icon: categoriesIcon,
    description: "Academic, market, and data research roles.",
  },
  {
    id: "video-editing",
    name: "Video Editing",
    group: "Design & Art",
    jobs: 84,
    subscribers: 973,
    icon: categoriesIcon,
    description: "Video production, editing, and motion design.",
  },
  {
    id: "photography",
    name: "Photography",
    group: "Design & Art",
    jobs: 22,
    subscribers: 189,
    icon: categoriesIcon,
    description: "Photography and visual media jobs.",
  },
];
