import productDesignerIcon from "../assets/icons/productDesignerIcon.svg";
import uiuxIcon from "../assets/icons/uiuxIcon.svg";
import pythonIcon from "../assets/icons/pythonIcon.svg";
import juniordevopsIcon from "../assets/icons/juniordevopsIcon.svg";

export const JOBS = [
  {
    id: "1",
    title: "Product Designer",
    icon: productDesignerIcon,
    posted: Date.now(),

    description:
      "KeplerLab is a VC-backed, stealth, application-only platform for senior product designers to team up with the best companies on their next big thing.",
    company: "KeplerLab",
    type: "Full-Time",
    level: "Intermediate",
    salary: "$15/hr",
    qualifications: ["Bachelor’s degree in Design or related field"],
    experience: ["2+ years experience in product design"],
    skills: ["Figma", "UI Design", "UX Research"],
    tags: ["UI", "UX", "Design"],
  },
  {
    id: "2",
    title: "UI/UX Designer",
    icon: uiuxIcon,
    posted: Date.now(),
    description:
      "We’re looking for an experienced UI designer to design and shape unique user-centric experiences.",
    company: "KeplerLab",
    type: "Part-Time",
    level: "Expert",
    salary: "$25–30/hr",
    qualifications: ["Strong UI portfolio"],
    experience: ["3+ years UI/UX experience"],
    skills: ["Figma", "Prototyping"],
    tags: ["UI", "UX"],
  },
  {
    id: "3",
    title: "Senior Python Developer",
    icon: pythonIcon,
    posted: Date.now(),
    description: "Develop scalable backend services using Python and Django.",
    company: "Infosys",
    type: "Full-Time",
    level: "Intermediate",
    salary: "$20/hr",
    qualifications: ["CS Degree or equivalent"],
    experience: ["Python backend experience"],
    skills: ["Python", "Django", "PostgreSQL"],
    tags: ["Python", "Backend"],
  },
  {
    id: "4",
    title: "Junior Python Developer",
    icon: juniordevopsIcon,
    posted: Date.now(),
    description: "Work with senior developers on backend systems.",
    company: "Infosys",
    type: "Full-Time",
    level: "Junior",
    salary: "$20/hr",
    qualifications: ["Basic Python knowledge"],
    experience: ["Internship or projects"],
    skills: ["Python"],
    tags: ["Python", "Junior"],
  },
  {
    id: "5",
    title: "Graphic Design Specialist",
    icon: uiuxIcon,
    posted: Date.now(),
    description:
      "We need one to Designs and maintains prospect websites including graphic development, regular site updates, usability reviews and traffic reporting.",
    company: "Infosys",
    type: "Full-Time",
    level: "Intermediate",
    salary: "$20/hr",
    qualifications: [
      "Bachelor's degree with major in graphic design or a related field from an accredited college or university preferred.",
    ],
    experience: [
      "Four (4) years of graphic/web design experience or equivalent combination of education and experience required. - rrrrrrrrrrrrrrrrr gggggggggg",
    ],
    skills: [
      "Excellent knowledge of graphic and photo software - Good knowledge of web technology - Excellent oral and written communication, including presentation skills - PC literate, including Microsoft Office products - Strong organizational skills - Excellent interpersonal skills - Ability to work on multiple projects and meet deadlines - Ability to work in a team environment - Ability to meet or exceed Performance Competencies",
    ],
    detailDescription: [
      "For a career path that is both challenging and rewarding, join Sedgwick’s talented team of 27,000 colleagues around the globe. Sedgwick is a leading provider of technology-enabled risk, benefits and integrated business solutions. Taking care of people is at the heart of everything we do. Millions of people and organizations count on Sedgwick each year to take care of their needs when they face a major life event or something unexpected happens. Whether they have a workplace injury, suffer property or financial loss or damage from a natural or manmade disaster, are involved in an auto or other type of accident, or need time away from work for the birth of a child or another medical situation, we are here to provide compassionate care and expert guidance. Our clients depend on our talented colleagues to take care of their most valuable assets—their employees, their customers and their property. At Sedgwick, caring counts®. Join our team of creative and caring people of all backgrounds, and help us make a difference in the lives of others.",

      "PRIMARY PURPOSE: To design and produce presentations, technical and conceptual web graphics, interactive marketing materials, and print materials.",
    ],
    tags: ["Java", "User Interface", "C++", "Python", "Flutter"],
  },
  // ✅ ADD THESE AFTER ID "5" — DO NOT CHANGE YOUR FIRST 5

  {
    id: "6",
    title: "Frontend React Developer",
    icon: uiuxIcon,
    posted: Date.now(),
    description:
      "Build responsive web interfaces using React and modern CSS frameworks.",
    company: "NovaTech",
    type: "Full-Time",
    level: "Intermediate",
    salary: "$28/hr",
    qualifications: ["Bachelor’s degree in Computer Science or related field"],
    experience: ["2–4 years experience with React"],
    skills: ["React", "JavaScript", "Tailwind CSS"],
    tags: ["Frontend", "React", "Web"],
  },
  {
    id: "7",
    title: "Backend Node.js Engineer",
    icon: pythonIcon,
    posted: Date.now(),
    description:
      "Develop scalable APIs and microservices for cloud applications.",
    company: "CloudForge",
    type: "Remote",
    level: "Senior",
    salary: "$40/hr",
    qualifications: ["CS degree or equivalent experience"],
    experience: ["5+ years backend development"],
    skills: ["Node.js", "Express", "MongoDB"],
    tags: ["Backend", "Node", "API"],
  },
  {
    id: "8",
    title: "Mobile App Developer (Flutter)",
    icon: juniordevopsIcon,
    posted: Date.now(),
    description: "Create cross-platform mobile applications with Flutter.",
    company: "AppNest",
    type: "Contract",
    level: "Intermediate",
    salary: "$30/hr",
    qualifications: ["Experience with mobile development"],
    experience: ["2+ years Flutter experience"],
    skills: ["Flutter", "Dart", "Firebase"],
    tags: ["Mobile", "Flutter"],
  },
  {
    id: "9",
    title: "DevOps Engineer",
    icon: juniordevopsIcon,
    posted: Date.now(),
    description: "Automate CI/CD pipelines and manage cloud infrastructure.",
    company: "InfraStack",
    type: "Full-Time",
    level: "Senior",
    salary: "$45/hr",
    qualifications: ["Degree in IT or Engineering"],
    experience: ["4+ years DevOps experience"],
    skills: ["AWS", "Docker", "Kubernetes"],
    tags: ["DevOps", "Cloud"],
  },
  {
    id: "10",
    title: "QA Automation Engineer",
    icon: pythonIcon,
    posted: Date.now(),
    description:
      "Design and maintain automated test suites for web applications.",
    company: "TestPro",
    type: "Full-Time",
    level: "Intermediate",
    salary: "$26/hr",
    qualifications: ["Knowledge of software testing principles"],
    experience: ["2+ years QA automation"],
    skills: ["Selenium", "Python", "Cypress"],
    tags: ["QA", "Automation"],
  },
  {
    id: "11",
    title: "Data Analyst",
    icon: pythonIcon,
    posted: "2 days ago",
    description: "Analyze datasets and generate actionable business insights.",
    company: "DataWave",
    type: "Part-Time",
    level: "Intermediate",
    salary: "$22/hr",
    qualifications: ["Degree in Statistics, Math, or CS"],
    experience: ["Experience with data analysis tools"],
    skills: ["Python", "SQL", "Power BI"],
    tags: ["Data", "Analytics"],
  },
  {
    id: "12",
    title: "Machine Learning Engineer",
    icon: pythonIcon,
    posted: "1 week ago",
    description: "Build and deploy machine learning models into production.",
    company: "AI Labs",
    type: "Full-Time",
    level: "Expert",
    salary: "$55/hr",
    qualifications: ["Advanced degree preferred"],
    experience: ["5+ years ML experience"],
    skills: ["Python", "TensorFlow", "Scikit-learn"],
    tags: ["AI", "ML"],
  },
  {
    id: "13",
    title: "Cybersecurity Analyst",
    icon: juniordevopsIcon,
    posted: "4 days ago",
    description: "Monitor systems and protect against security threats.",
    company: "SecureNet",
    type: "Full-Time",
    level: "Intermediate",
    salary: "$35/hr",
    qualifications: ["Security certification preferred"],
    experience: ["3+ years cybersecurity experience"],
    skills: ["Network Security", "SIEM", "Risk Assessment"],
    tags: ["Security", "Cyber"],
  },
  {
    id: "14",
    title: "Technical Support Engineer",
    icon: juniordevopsIcon,
    posted: "8 hrs ago",
    description:
      "Provide technical assistance and troubleshoot customer issues.",
    company: "HelpDesk Plus",
    type: "Shift-Based",
    level: "Junior",
    salary: "$18/hr",
    qualifications: ["IT diploma or equivalent"],
    experience: ["Entry-level or internship"],
    skills: ["Troubleshooting", "Networking Basics"],
    tags: ["Support", "IT"],
  },
  {
    id: "15",
    title: "UI Motion Designer",
    icon: uiuxIcon,
    posted: "1 day ago",
    description:
      "Create smooth animations and micro-interactions for web apps.",
    company: "PixelFlow",
    type: "Contract",
    level: "Intermediate",
    salary: "$32/hr",
    qualifications: ["Strong motion design portfolio"],
    experience: ["2+ years motion/UI design"],
    skills: ["After Effects", "Lottie", "Figma"],
    tags: ["UI", "Animation"],
  },
  {
    id: "16",
    title: "Technical Writer",
    icon: productDesignerIcon,
    posted: "3 days ago",
    description:
      "Write clear technical documentation for developers and users.",
    company: "DocuWorks",
    type: "Remote",
    level: "Intermediate",
    salary: "$24/hr",
    qualifications: ["Excellent written communication"],
    experience: ["Experience writing technical docs"],
    skills: ["Markdown", "API Docs", "Research"],
    tags: ["Documentation", "Writing"],
  },
  {
    id: "17",
    title: "Blockchain Developer",
    icon: pythonIcon,
    posted: "5 days ago",
    description: "Develop smart contracts and decentralized applications.",
    company: "ChainCore",
    type: "Full-Time",
    level: "Senior",
    salary: "$50/hr",
    qualifications: ["Strong blockchain fundamentals"],
    experience: ["3+ years blockchain development"],
    skills: ["Solidity", "Ethereum", "Web3.js"],
    tags: ["Blockchain", "Web3"],
  },
  {
    id: "18",
    title: "Game UI Designer",
    icon: uiuxIcon,
    posted: "9 hrs ago",
    description: "Design immersive user interfaces for mobile and PC games.",
    company: "PlayForge",
    type: "Full-Time",
    level: "Intermediate",
    salary: "$27/hr",
    qualifications: ["Game design or UI background"],
    experience: ["2+ years game UI experience"],
    skills: ["Figma", "Unity UI", "Prototyping"],
    tags: ["Games", "UI"],
  },
  {
    id: "19",
    title: "Cloud Solutions Architect",
    icon: juniordevopsIcon,
    posted: "2 days ago",
    description: "Design scalable cloud architectures for enterprise clients.",
    company: "SkyCompute",
    type: "Full-Time",
    level: "Expert",
    salary: "$60/hr",
    qualifications: ["Cloud certification preferred"],
    experience: ["6+ years cloud architecture"],
    skills: ["AWS", "Azure", "System Design"],
    tags: ["Cloud", "Architecture"],
  },
  {
    id: "20",
    title: "AI Prompt Engineer",
    icon: pythonIcon,
    posted: "6 hrs ago",
    description: "Design and optimize prompts for AI-powered applications.",
    company: "PromptlyAI",
    type: "Remote",
    level: "Intermediate",
    salary: "$34/hr",
    qualifications: ["Understanding of LLMs"],
    experience: ["Experience working with AI tools"],
    skills: ["Prompt Engineering", "LLMs", "Python"],
    tags: ["AI", "LLM"],
  },
  {
    id: "21",
    title: "Junior Frontend Developer",
    icon: uiuxIcon,
    posted: "3 hrs ago",
    description: "Assist in building responsive UI components for web apps.",
    company: "BrightWeb",
    type: "Full-Time",
    level: "Junior",
    salary: "$18/hr",
    qualifications: ["Basic HTML, CSS, JS knowledge"],
    experience: ["0–1 year frontend experience"],
    skills: ["HTML", "CSS", "JavaScript"],
    tags: ["Frontend", "Junior"],
  },
  {
    id: "22",
    title: "Senior React Engineer",
    icon: uiuxIcon,
    posted: "1 day ago",
    description: "Lead frontend architecture and React best practices.",
    company: "ScaleUI",
    type: "Remote",
    level: "Senior",
    salary: "$48/hr",
    qualifications: ["Advanced React knowledge"],
    experience: ["5+ years frontend experience"],
    skills: ["React", "Redux", "Performance Optimization"],
    tags: ["React", "Frontend"],
  },
  {
    id: "23",
    title: "Backend Java Developer",
    icon: pythonIcon,
    posted: "6 hrs ago",
    description: "Build enterprise backend systems using Java and Spring Boot.",
    company: "Enterprisely",
    type: "Full-Time",
    level: "Intermediate",
    salary: "$32/hr",
    qualifications: ["Java certification preferred"],
    experience: ["3+ years Java backend"],
    skills: ["Java", "Spring Boot", "MySQL"],
    tags: ["Backend", "Java"],
  },
  {
    id: "24",
    title: "iOS Mobile Developer",
    icon: juniordevopsIcon,
    posted: "2 days ago",
    description: "Develop native iOS applications using Swift.",
    company: "AppCore",
    type: "Contract",
    level: "Intermediate",
    salary: "$36/hr",
    qualifications: ["iOS development experience"],
    experience: ["2+ years iOS apps"],
    skills: ["Swift", "Xcode", "UIKit"],
    tags: ["Mobile", "iOS"],
  },
  {
    id: "25",
    title: "Android Developer",
    icon: juniordevopsIcon,
    posted: "10 hrs ago",
    description: "Build and maintain Android applications.",
    company: "DroidLabs",
    type: "Full-Time",
    level: "Intermediate",
    salary: "$34/hr",
    qualifications: ["Android SDK knowledge"],
    experience: ["2+ years Android development"],
    skills: ["Kotlin", "Java", "Android Studio"],
    tags: ["Mobile", "Android"],
  },
  {
    id: "26",
    title: "Full Stack Developer",
    icon: pythonIcon,
    posted: "4 days ago",
    description: "Work across frontend and backend to deliver full solutions.",
    company: "StackWorks",
    type: "Full-Time",
    level: "Intermediate",
    salary: "$38/hr",
    qualifications: ["Full stack experience"],
    experience: ["3+ years full stack"],
    skills: ["React", "Node.js", "PostgreSQL"],
    tags: ["Full Stack", "Web"],
  },
  {
    id: "27",
    title: "Junior QA Tester",
    icon: juniordevopsIcon,
    posted: "1 day ago",
    description: "Manually test applications and report bugs.",
    company: "BugTrack",
    type: "Part-Time",
    level: "Junior",
    salary: "$16/hr",
    qualifications: ["Basic testing knowledge"],
    experience: ["Entry-level"],
    skills: ["Manual Testing", "Bug Reporting"],
    tags: ["QA", "Junior"],
  },
  {
    id: "28",
    title: "Site Reliability Engineer",
    icon: juniordevopsIcon,
    posted: "3 days ago",
    description: "Ensure reliability and uptime of distributed systems.",
    company: "ReliantOps",
    type: "Full-Time",
    level: "Senior",
    salary: "$52/hr",
    qualifications: ["Strong systems background"],
    experience: ["5+ years SRE experience"],
    skills: ["Linux", "Monitoring", "Automation"],
    tags: ["SRE", "DevOps"],
  },
  {
    id: "29",
    title: "UI Accessibility Specialist",
    icon: uiuxIcon,
    posted: "7 hrs ago",
    description: "Improve accessibility compliance across UI products.",
    company: "AccessFirst",
    type: "Contract",
    level: "Intermediate",
    salary: "$29/hr",
    qualifications: ["Accessibility standards knowledge"],
    experience: ["2+ years accessibility work"],
    skills: ["WCAG", "ARIA", "UX"],
    tags: ["Accessibility", "UI"],
  },
  {
    id: "30",
    title: "Product Manager (Tech)",
    icon: productDesignerIcon,
    posted: "5 days ago",
    description: "Lead product planning and execution for tech teams.",
    company: "Productive",
    type: "Full-Time",
    level: "Senior",
    salary: "$45/hr",
    qualifications: ["Technical PM experience"],
    experience: ["4+ years product management"],
    skills: ["Roadmapping", "Agile", "Stakeholder Management"],
    tags: ["Product", "Management"],
  },
  {
    id: "31",
    title: "AI Research Assistant",
    icon: pythonIcon,
    posted: "8 hrs ago",
    description: "Support AI research and model experimentation.",
    company: "DeepThink",
    type: "Part-Time",
    level: "Junior",
    salary: "$20/hr",
    qualifications: ["ML fundamentals"],
    experience: ["Academic or project experience"],
    skills: ["Python", "PyTorch", "Data Prep"],
    tags: ["AI", "Research"],
  },
  {
    id: "32",
    title: "Cloud Support Engineer",
    icon: juniordevopsIcon,
    posted: "1 day ago",
    description: "Support customers using cloud platforms.",
    company: "CloudAssist",
    type: "Shift-Based",
    level: "Intermediate",
    salary: "$24/hr",
    qualifications: ["Cloud basics"],
    experience: ["Support experience preferred"],
    skills: ["AWS", "Troubleshooting"],
    tags: ["Cloud", "Support"],
  },
  {
    id: "33",
    title: "AR/VR Developer",
    icon: pythonIcon,
    posted: "6 days ago",
    description: "Build immersive AR/VR experiences.",
    company: "ImmersionX",
    type: "Contract",
    level: "Intermediate",
    salary: "$42/hr",
    qualifications: ["AR/VR development experience"],
    experience: ["2+ years Unity"],
    skills: ["Unity", "C#", "XR"],
    tags: ["AR", "VR"],
  },
  {
    id: "34",
    title: "Embedded Systems Engineer",
    icon: juniordevopsIcon,
    posted: "2 days ago",
    description: "Develop firmware for embedded devices.",
    company: "EmbedTech",
    type: "Full-Time",
    level: "Senior",
    salary: "$46/hr",
    qualifications: ["Embedded systems degree"],
    experience: ["5+ years embedded development"],
    skills: ["C", "C++", "Microcontrollers"],
    tags: ["Embedded", "Firmware"],
  },
  {
    id: "35",
    title: "Low-Code Developer",
    icon: uiuxIcon,
    posted: "9 hrs ago",
    description: "Build applications using low-code platforms.",
    company: "QuickApps",
    type: "Remote",
    level: "Intermediate",
    salary: "$26/hr",
    qualifications: ["Low-code tools experience"],
    experience: ["2+ years app building"],
    skills: ["OutSystems", "PowerApps"],
    tags: ["Low-Code", "Apps"],
  },
  {
    id: "36",
    title: "No-Code Automation Specialist",
    icon: uiuxIcon,
    posted: "1 day ago",
    description: "Automate workflows using no-code tools.",
    company: "FlowLess",
    type: "Contract",
    level: "Intermediate",
    salary: "$28/hr",
    qualifications: ["Automation mindset"],
    experience: ["Zapier/Make experience"],
    skills: ["Zapier", "Make", "Airtable"],
    tags: ["No-Code", "Automation"],
  },
  {
    id: "37",
    title: "Junior Data Engineer",
    icon: pythonIcon,
    posted: "3 hrs ago",
    description: "Assist in building data pipelines.",
    company: "PipeData",
    type: "Full-Time",
    level: "Junior",
    salary: "$19/hr",
    qualifications: ["Data fundamentals"],
    experience: ["Entry-level"],
    skills: ["SQL", "Python", "ETL"],
    tags: ["Data", "Junior"],
  },
  {
    id: "38",
    title: "Senior Data Engineer",
    icon: pythonIcon,
    posted: "2 days ago",
    description: "Design scalable data infrastructure.",
    company: "BigScale",
    type: "Full-Time",
    level: "Senior",
    salary: "$50/hr",
    qualifications: ["Advanced data engineering"],
    experience: ["5+ years data systems"],
    skills: ["Spark", "Kafka", "BigQuery"],
    tags: ["Data", "Engineering"],
  },
  {
    id: "39",
    title: "UX Researcher",
    icon: uiuxIcon,
    posted: "4 days ago",
    description: "Conduct user research and usability testing.",
    company: "UserFirst",
    type: "Part-Time",
    level: "Intermediate",
    salary: "$27/hr",
    qualifications: ["Research background"],
    experience: ["2+ years UX research"],
    skills: ["User Interviews", "Usability Testing"],
    tags: ["UX", "Research"],
  },
  {
    id: "40",
    title: "IT Systems Administrator",
    icon: juniordevopsIcon,
    posted: "5 hrs ago",
    description: "Maintain internal IT systems and networks.",
    company: "NetCore",
    type: "Full-Time",
    level: "Intermediate",
    salary: "$29/hr",
    qualifications: ["IT administration experience"],
    experience: ["3+ years sysadmin"],
    skills: ["Windows Server", "Networking"],
    tags: ["IT", "Systems"],
  },
  {
    id: "41",
    title: "Penetration Tester",
    icon: juniordevopsIcon,
    posted: "6 days ago",
    description: "Perform security testing on applications.",
    company: "HackSafe",
    type: "Contract",
    level: "Senior",
    salary: "$48/hr",
    qualifications: ["Security certifications preferred"],
    experience: ["4+ years pentesting"],
    skills: ["Ethical Hacking", "OWASP"],
    tags: ["Security", "Testing"],
  },
  {
    id: "42",
    title: "CRM Implementation Specialist",
    icon: productDesignerIcon,
    posted: "1 week ago",
    description: "Implement and customize CRM systems.",
    company: "ClientFlow",
    type: "Full-Time",
    level: "Intermediate",
    salary: "$31/hr",
    qualifications: ["CRM experience"],
    experience: ["2+ years CRM implementation"],
    skills: ["Salesforce", "Configuration"],
    tags: ["CRM", "Business"],
  },
  {
    id: "43",
    title: "Tech Recruiter",
    icon: productDesignerIcon,
    posted: "2 days ago",
    description: "Recruit technical talent for startups.",
    company: "HireFast",
    type: "Full-Time",
    level: "Intermediate",
    salary: "$23/hr",
    qualifications: ["Recruiting experience"],
    experience: ["2+ years tech recruiting"],
    skills: ["Sourcing", "Interviewing"],
    tags: ["Recruiting", "HR"],
  },
  {
    id: "44",
    title: "Build & Release Engineer",
    icon: juniordevopsIcon,
    posted: "3 hrs ago",
    description: "Manage build pipelines and release processes.",
    company: "ReleaseHub",
    type: "Full-Time",
    level: "Senior",
    salary: "$44/hr",
    qualifications: ["CI/CD expertise"],
    experience: ["4+ years DevOps"],
    skills: ["CI/CD", "Jenkins", "Git"],
    tags: ["Build", "DevOps"],
  },
  {
    id: "45",
    title: "Platform Engineer",
    icon: juniordevopsIcon,
    posted: "4 days ago",
    description: "Build internal developer platforms.",
    company: "PlatformX",
    type: "Full-Time",
    level: "Senior",
    salary: "$47/hr",
    qualifications: ["Platform engineering experience"],
    experience: ["5+ years"],
    skills: ["Kubernetes", "Terraform"],
    tags: ["Platform", "Engineering"],
  },
  {
    id: "46",
    title: "Web Performance Engineer",
    icon: uiuxIcon,
    posted: "2026-01-12T09:41:23.112Z",
    description: "Optimize web applications for speed and performance.",
    company: "Speedify",
    type: "Contract",
    level: "Intermediate",
    salary: "$33/hr",
    qualifications: ["Performance optimization knowledge"],
    experience: ["3+ years frontend"],
    skills: ["Lighthouse", "Web Vitals"],
    tags: ["Performance", "Web"],
  },
  {
    id: "47",
    title: "Technical SEO Specialist",
    icon: uiuxIcon,
    posted: "2026-01-12T09:41:23.112Z",
    description: "Improve technical SEO across websites.",
    company: "RankBoost",
    type: "Remote",
    level: "Intermediate",
    salary: "$24/hr",
    qualifications: ["SEO experience"],
    experience: ["2+ years SEO"],
    skills: ["SEO", "Analytics", "Search Console"],
    tags: ["SEO", "Marketing"],
  },
  {
    id: "48",
    title: "Digital Transformation Consultant",
    icon: productDesignerIcon,
    posted: "2026-01-12T09:41:23.112Z",
    description: "Guide companies through digital transformation.",
    company: "TransformIQ",
    type: "Contract",
    level: "Expert",
    salary: "$58/hr",
    qualifications: ["Consulting background"],
    experience: ["7+ years"],
    skills: ["Strategy", "Digital Tools"],
    tags: ["Consulting", "Digital"],
  },
  {
    id: "49",
    title: "Firmware Test Engineer",
    icon: juniordevopsIcon,
    posted: "2026-01-12T09:41:23.112Z",
    description: "Test firmware on embedded devices.",
    company: "ChipWorks",
    type: "Full-Time",
    level: "Intermediate",
    salary: "$30/hr",
    qualifications: ["Embedded testing knowledge"],
    experience: ["2+ years testing"],
    skills: ["Firmware Testing", "Debugging"],
    tags: ["Firmware", "QA"],
  },
  {
    id: "50",
    title: "AI Ethics Analyst",
    icon: pythonIcon,
    posted: "2026-01-12T09:41:23.112Z",
    description: "Assess ethical implications of AI systems.",
    company: "EthicAI",
    type: "Remote",
    level: "Expert",
    salary: "$46/hr",
    qualifications: ["AI ethics knowledge"],
    experience: ["Research or policy experience"],
    skills: ["AI Ethics", "Policy Analysis"],
    tags: ["AI", "Ethics"],
  },
];
