export const TAGS = [
  {
    id: "javascript",
    name: "JavaScript",
    jobs: 14,
    subscribers: 173,
  },
  {
    id: "python",
    name: "Python",
    jobs: 10,
    subscribers: 30,
  },
  {
    id: "golang",
    name: "Golang",
    jobs: 17,
    subscribers: 53,
  },
  {
    id: "flutter",
    name: "Flutter",
    jobs: 85,
    subscribers: 350,
  },
  {
    id: "reactjs",
    name: "ReactJS",
    jobs: 101,
    subscribers: 430,
  },
  {
    id: "sveltejs",
    name: "SvelteJS",
    jobs: 23,
    subscribers: 25,
  },
  {
    id: "javascript",
    name: "JavaScript",
    jobs: 14,
    subscribers: 173,
  },
  {
    id: "python",
    name: "Python",
    jobs: 10,
    subscribers: 30,
  },
  {
    id: "golang",
    name: "Golang",
    jobs: 17,
    subscribers: 53,
  },
  {
    id: "flutter",
    name: "Flutter",
    jobs: 85,
    subscribers: 350,
  },
  {
    id: "reactjs",
    name: "ReactJS",
    jobs: 101,
    subscribers: 430,
  },
  {
    id: "sveltejs",
    name: "SvelteJS",
    jobs: 23,
    subscribers: 25,
  },
  { id: "typescript", name: "TypeScript", jobs: 78, subscribers: 412 },
  { id: "nodejs", name: "Node.js", jobs: 92, subscribers: 530 },
  { id: "nextjs", name: "Next.js", jobs: 64, subscribers: 388 },
  { id: "vuejs", name: "Vue.js", jobs: 41, subscribers: 244 },
  { id: "angular", name: "Angular", jobs: 36, subscribers: 219 },
  { id: "django", name: "Django", jobs: 55, subscribers: 301 },
  { id: "fastapi", name: "FastAPI", jobs: 27, subscribers: 167 },
  { id: "laravel", name: "Laravel", jobs: 48, subscribers: 260 },
  { id: "php", name: "PHP", jobs: 34, subscribers: 195 },
  { id: "java", name: "Java", jobs: 73, subscribers: 421 },
  { id: "springboot", name: "Spring Boot", jobs: 46, subscribers: 287 },
  { id: "csharp", name: "C#", jobs: 39, subscribers: 232 },
  { id: "dotnet", name: ".NET", jobs: 52, subscribers: 310 },
  { id: "kotlin", name: "Kotlin", jobs: 26, subscribers: 149 },
  { id: "swift", name: "Swift", jobs: 21, subscribers: 133 },
  { id: "android", name: "Android", jobs: 67, subscribers: 378 },
  { id: "ios", name: "iOS", jobs: 29, subscribers: 172 },
  { id: "devops", name: "DevOps", jobs: 84, subscribers: 490 },
  { id: "docker", name: "Docker", jobs: 58, subscribers: 344 },
  { id: "kubernetes", name: "Kubernetes", jobs: 44, subscribers: 298 },
];
